### ISSUE TITLE
Song analysis

### ISSUE THREAD

**Issue by harryworld** [MindFundStudio/MixablyMac#3]
Wait for the stand alone binary
Relate to #2

**Comment by leotumwattana** [comment]
### NSTask Basics

http://stackoverflow.com/questions/412562/execute-a-terminal-command-from-a-cocoa-app
http://www.raywenderlich.com/36537/nstask-tutorial
http://practicalswift.com/2014/06/25/how-to-execute-shell-commands-from-swift/

### NSTask Notifications

http://stackoverflow.com/questions/17788267/get-notification-of-task-progress-from-nstask

### Bundling Binary

http://www.smallersystems.com/blog/2008/05/embedding-a-command-line-tool-within-a-cocoa-application/
http://stackoverflow.com/questions/20856864/how-can-i-code-sign-a-bundled-executable-file-in-a-mac-app-using-xcode5

**Comment by leotumwattana** [comment]
**MXOperationAnalysis done. Possible issue:**
- [ ] Sandbox issues with blackbox
- [x] Special character for song path

**TODO:**
- [x] Run analysis on new songs #18 
- [x] Persist results to Realm

**Comment by harryworld** [comment]
I have 2 songs not able to process, the command line works, but not within Mixably

```
➜  MixablyMac git:(develop) ✗ ./blackbox /Users/harryng/Music/iTunes/iTunes\ Media/Music/Compilations/\#Love/2-14\ Your\ Body\ Is\ a\ Wonderland.m4a -s

{"musicPath":"/Users/harryng/Music/iTunes/iTunes Media/Music/Compilations/#Love/2-14 Your Body Is a Wonderland.m4a","rmsEnergy":205.112,"intensity":610.684,"rhythmStrength":2858.95,"tempo":95.57342565100093,"tonality":"F minor","bins":[2032.855,650.6205,433.432,280.571,109.22049999999999,59.730050000000006,9.570515]}

➜  MixablyMac git:(develop) ✗ ./blackbox /Users/harryng/Music/iTunes/iTunes\ Media/Music/Compilations/\#Love/2-17\ Careless\ Whisper.m4a -s

{"musicPath":"/Users/harryng/Music/iTunes/iTunes Media/Music/Compilations/#Love/2-17 Careless Whisper.m4a","rmsEnergy":132.27800000000002,"intensity":398.999,"rhythmStrength":2508.77,"tempo":155.8943518075219,"tonality":"D minor","bins":[1183.205,593.894,242.1955,144.8065,80.4059,39.59695,6.17348]}
```

**Comment by harryworld** [comment]
Wait for feedback
`Optional("ERROR PARSING FREQ BINS\n")`
