### ISSUE TITLE
Shows Mixably Layout

### ISSUE THREAD

**Issue by harryworld** [MindFundStudio/MixablyMac#8]
- [x] Action buttons to save mood list #6 
- [x] Filter songs according to mood filter #9
- [x] Controls of mood filter #10
